In [ ]:
lista = [1,5,7]

def media(lista):
    m = lista.mean()
    return m

In [ ]:
# calculo da media de lista 

def calcular_media(lista):
    return sum(lista) / len(lista)

numeros = [10,20,30,40,50]
media = calcular_media(numeros)
print("A media dos numeros é", media)

In [ ]:
# Encontrando o maior valor dentro da lista
def maior(lista):
    return max(lista)

numeros = [1,2,3,4,5]
maximo = maior(numeros)
print(maximo)

In [ ]:
# Verificando se todos os elementos de uma lista são positivos
def positivo_negativo(lista):
    positivos = [num for num in lista if num > 0]
    negativos = [num for num in lista if num < 0]
    return positivos, negativos

numeros = [10,-20,3,40,50,-3,7,8]
positivos, negativos = positivo_negativo(numeros)
print(positivos)
print(negativos)

In [ ]:
lista = [10,2,7,9,10,22,5]

def media_soma(lista):
    media = sum(lista) / len(lista)
    soma = sum(lista)
    return media, soma

numeros = [10,2,7,9,10,22,5]
media, soma = media_soma(numeros)
print(media)
print(soma)

In [ ]:
def min_max(lista):
    minimo = min(lista)
    maximo = max(lista)
    return minimo, maximo

numeros = [10,2,7,9,10,22,5]
minimo, maximo = min_max(lista)
print(minimo)
print(maximo)



In [ ]:
# retorne a min, max, soma e media 

def quatro(lista):
    minimo = min(lista)
    maximo = max(lista)
    soma = sum(lista)
    media = sum(lista) / len(lista)
    return minimo, maximo, soma, media

numbers = [10,2,7,9,10,22,5]
minimo, maximo, soma, media = quatro(numbers)
print(minimo)
print(maximo)
print(soma)
print(media)

In [ ]:
def soma_quadrado(lista):
    return sum(num**2 for num in lista)

numbers = [10,2,7,9,10,22,5]
result = soma_quadrado(numbers)
print(result)


In [ ]:
# Conte quantas vezes um determinado elemento aparece em uma lista

def contar(lista,elemento):
    return lista.count(elemento)

numeros = [1,2,3,4,5,6]
elemento = 3
ocorrencias = contar(numeros,elemento)
print("O elemento", elemento, "aparece", ocorrencias, "vezes na lista")




In [ ]:
# Inverter lista

def inverter_lista(lista):
    return lista[::-1]

numeros = [1,2,3,4,5]
lista_invertida = inverter_lista(numeros)
print("Lista invertida", lista_invertida)

In [ ]:
# verifique se uma lista está ordenada de forma crescente

def esta_ordenada_crescente(lista):
    return lista == sorted(lista)

numeros = [1,2,3,4,5]
esta_ordenada = esta_ordenada_crescente(numeros)
print("A lista está ordenada de forma crescente ?", esta_ordenada)


In [ ]:
# remover valores duplicados de uma lista 

def remover_duplicados(lista):
    return list(set(lista))

numeros = [1,1,3,4,5,5,6]
sem_duplicados = remover_duplicados(numeros)
print("Lista elementos duplicados", sem_duplicados)


In [ ]:
pip install pandas

In [1]:
import pandas as pd


In [2]:
dados = pd.read_csv(r'C:\Users\logonrmlocal\Desktop\pyhon_aula3\manutencao_preditiva.csv')


In [ ]:
dados

In [ ]:

x = dados[['UDI']]
y1 = dados[['Temperatura Ar [K]']]
y2 = dados[['Temperatura Processo [K]']]


In [ ]:
x, y

In [ ]:
pip install matplotlib

In [ ]:
import matplotlib.pyplot as plt

plt.plot(x,y1,x,y2)
plt.show()

In [ ]:
dados_filtrados = dados.head(5)

rotacao = dados_filtrados[['Velocidade Rotacao [rpm]']] 
torque = dados_filtrados[['Torque [Nm]']]




In [ ]:
torque

In [ ]:
rotacao

In [ ]:
dados_novo = dados_filtrados[['Torque [Nm]','Velocidade Rotacao [rpm]']].values
dados_novo

In [ ]:
pip install numpy


In [15]:
import numpy as np
soma_elementos = np.sum(dados_novo)
print(soma_elementos)

NameError: name 'dados_novo' is not defined

In [ ]:
valores_minimos_por_linha = np.min(dados_novo, axis=1)
print("Valores minimos em cada linha da matriz",valores_minimos_por_linha )



In [ ]:
medias_por_coluna = np.mean(dados_novo, axis=0)
print("Média de cada coluna da matriz,", medias_por_coluna)

In [ ]:
matriz_transposta = np.transpose(dados_novo)
matriz_transposta

In [3]:
# Selecionar data frame 1 : Temperatura do ar e torque
# Selecionar data frame 2 : Temperatura do processo e velocidade de rotação

# 1
dados1 = dados[['Temperatura Ar [K]', 'Torque [Nm]']]
dados1

dados2 = dados[['Temperatura Processo [K]','Velocidade Rotacao [rpm]']]
dados2





Temperatura Processo [K]  Velocidade Rotacao [rpm]
0                        308.6                      1551
1                        308.7                      1408
2                        308.5                      1498
3                        308.6                      1433
4                        308.7                      1408
...                        ...                       ...
9995                     308.4                      1604
9996                     308.4                      1632
9997                     308.6                      1645
9998                     308.7                      1408
9999                     308.7                      1500

[10000 rows x 2 columns]

In [4]:
# 2
dados1.head(10)
dados2.iloc[15:25]

Temperatura Processo [K]  Velocidade Rotacao [rpm]
15                     309.2                      1542
16                     309.2                      1311
17                     309.2                      1410
18                     309.2                      1306
19                     309.3                      1632
20                     309.3                      1375
21                     309.3                      1450
22                     309.3                      1581
23                     309.4                      1758
24                     309.4                      1561

In [5]:

# 3
dados1 = dados1.head(10).values
dados2 = dados2.iloc[15:25].values


In [ ]:
pip install numpy

In [10]:
import numpy as np

In [13]:
# 4

soma_elementos1 = np.sum(dados1)
soma_elementos2 = np.sum(dados2)

print(soma_elementos1)
print(soma_elementos2)

3381.0
18018.8


In [ ]:
# 5

min1 = np.min(dados1, axis=0)
print(min1)
max1 = np.max(dados1, axis=0)
print(max1)

min2 = np.min(dados2, axis=0)
print(min2)
max2 = np.max(dados2, axis=0)
print(max2)

In [19]:

# 6
media1 = np.mean(dados1, axis=0)
print(media1)

media2 = np.mean(dados2, axis=0)
print(media2)

[298.19  39.91]
[ 309.28 1492.6 ]


In [23]:
# 7

matriz_transposta1 = np.transpose(dados1)
print(matriz_transposta1)

matriz_transposta2 = np.transpose(dados2)
print(matriz_transposta2)





[[298.1 298.2 298.1 298.2 298.2 298.1 298.1 298.1 298.3 298.5]
 [ 42.8  46.3  49.4  39.5  40.   41.9  42.4  40.2  28.6  28. ]]
[[ 309.2  309.2  309.2  309.2  309.3  309.3  309.3  309.3  309.4  309.4]
 [1542.  1311.  1410.  1306.  1632.  1375.  1450.  1581.  1758.  1561. ]]


In [25]:
# 8

media_transposta1 = np.mean(matriz_transposta1, axis=0)
print(media_transposta1)

media_transposta2 = np.mean(matriz_transposta2, axis=0)
print(media_transposta2)



[170.45 172.25 173.75 168.85 169.1  170.   170.25 169.15 163.45 163.25]
[ 925.6   810.1   859.6   807.6   970.65  842.15  879.65  945.15 1033.7
  935.2 ]
